---
title: "Bright Spots questions"
author: "Kara NEwhouse" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

# For U.S. Census Bureau data
library(tigris)


```

## Define Functions
```{r}
# Function for standardizing column names
## Load master key of variable names
variable_names = read_excel("../data-cleaning/data/handmade/variable_names.xlsx")

## Define function that maps variable names that should be replaced to their replacements
replace_names = function(df) {
  column_names = colnames(df)
  master_names_to_replace = c()
  master_new_name = c()
  for (i in column_names){
    
    names_to_replace = df[[i]]
    
    
    names_to_replace = names_to_replace[!is.na(names_to_replace)]
    new_names = rep(i, length(names_to_replace))
    
    master_names_to_replace = c(master_names_to_replace, names_to_replace)
    master_new_name = c(master_new_name, new_names)
    }
  
  master_key = setNames(nm = master_new_name, object = master_names_to_replace)
  
  return(master_key)
  
}
## Run function and store as list of keys
key = replace_names(variable_names)
```

## Load school list
```{r}
school_list <- read_csv("../data-cleaning/data/processed/etl_school_list.csv")
schools_all_years <- read_csv("../data-cleaning/data/processed/etl_school_full_data.csv")

```

## Teachers
```{r warning=FALSE,error=FALSE,message=FALSE}

# Define list of variables needed
climate_variables <- c("report_card_year", "district_nm", "school_nm", "schoolid", "schooltypecd", "tchreturn3yr_avg_pct_curr_yr")

# Teacher retention is in the classroom environment sheet
cl_env_18 <- read_excel("../data-cleaning/data/source/additional-info/ai-2018.xlsx", sheet = 9) %>%
  clean_names() %>% 
  select(climate_variables) %>% 
  rename(tch_retention_18 = tchreturn3yr_avg_pct_curr_yr)

cl_env_21 <- read_excel("../data-cleaning/data/source/additional-info/ai-2021.xlsx", sheet = 11) %>%
  clean_names() %>% 
  select(climate_variables) %>% 
  rename(tch_retention_21 = tchreturn3yr_avg_pct_curr_yr) %>% 
  mutate(report_card_year = as.character(report_card_year), tch_retention_21 = as.numeric(tch_retention_21))


drop_type <-c("D", "P")

teacher_retention <- cl_env_21 %>% 
  left_join(cl_env_18, by = "schoolid") %>% 
  filter(!(schooltypecd.x %in% drop_type)) %>% 
  select(1:5, 11, 6) %>% 
  mutate(change_over_time = tch_retention_21 - tch_retention_18) %>% 
  distinct(schoolid, change_over_time, .keep_all = TRUE) %>% 
  mutate(len_str = nchar(schoolid)) %>% 
  mutate(schoolid = if_else(len_str == 6, paste0("0", schoolid), schoolid)) %>% 
  select(-len_str) %>% 
  mutate(percent_change_over_time = (change_over_time/tch_retention_18)*100) %>% 
  arrange(desc(change_over_time))
  
tch_ret_30 <- teacher_retention %>% 
  arrange(desc(change_over_time)) %>% 
  head(30) %>% 
  select(school_nm.x)

tch_ret_pct_change_30 <- teacher_retention %>% 
  arrange(desc(percent_change_over_time)) %>% 
  head(30) %>% 
  select(school_nm.x)

diff_30_x <- tch_ret_30 %>% 
  anti_join(tch_ret_pct_change_30)

diff_30_y <- tch_ret_pct_change_30 %>% 
  anti_join(tch_ret_30)

diff <- diff_30_x %>% 
  bind_rows(diff_30_y)


```




## Reading
```{r}

#Among all schools: What are the 30 schools with the greatest increase in 3rd grade reading scores since 2017-2018
reading_2017 <- schools_all_years %>% 
  filter(year == "2017", type_x == "E") %>% 
  rename(e_pct_me_17 = e_pct_me)

reading_2021 <- schools_all_years %>% 
  filter(year == "2021", type_x == "E") %>% 
  rename(e_pct_me_21 = e_pct_me, pct_poverty_21 = pupils_in_poverty)


reading <- reading_2021 %>% 
  left_join(reading_2017, by = "school_id") %>% 
  mutate(change_over_time = e_pct_me_21 - e_pct_me_17) %>% 
  mutate(percent_change_over_time = (change_over_time/e_pct_me_17)*100) %>% 
  arrange(desc(percent_change_over_time)) %>% 
  select(school_id, school.x, type_x.x, district.x, district_alt.x, district_id.x, pct_poverty_21, e_pct_me_17, e_pct_me_21, change_over_time, percent_change_over_time)

#Among schools with more than 50 percent students living in poverty: What are the 30 schools that have made the greatest increase in 3rd grade reading scores since 2016-17?
reading_poverty <- reading %>% 
  filter(pct_poverty_21 >=50) %>% 
  filter(!is.na(percent_change_over_time)) %>% 
  arrange(desc(percent_change_over_time))


```

## Graduation
```{r}
# Among Title I schools: What are the 30 schools that have made the greatest increase in graduation rates in the past 5 years?
## Title I data by schools (w/school ID number): available here for school years since 2018-19: https://ed.sc.gov/policy/federal-education-programs/title-i/title-i-district-allocations-and-served-schools/ I've emailed SCDE to ask for 2017-18 and 2016-17, which will give us five years. 


# Among all high schools, what are the 30 schools that have made the greatest increase in graduation rates in the last 5 years? 
grad_variables <- c("year", "district", "school", "bedscode", "gpercent_overall")

grad_17 <- read_excel("../data-cleaning/data/source/additional-info/grad-2017.xls") %>%
  clean_names() %>%
  mutate(year = "2017") %>% 
  select(any_of(grad_variables))

grad_18 <- read_excel("../data-cleaning/data/source/additional-info/grad-2018.xlsx") %>%
  clean_names() %>% 
  mutate(year = "2018") %>% 
  select(any_of(grad_variables))

grad_19 <- read_excel("../data-cleaning/data/source/additional-info/grad-2019.xlsx") %>%
  clean_names() %>%
  mutate(year = "2019") %>% 
  select(any_of(grad_variables))

grad_20 <- read_excel("../data-cleaning/data/source/additional-info/grad-2020.xlsx") %>%
  clean_names() %>% 
  mutate(year = "2020") %>% 
  select(any_of(grad_variables))

grad_21 <- read_excel("../data-cleaning/data/source/additional-info/grad-2021.xlsx") %>%
  clean_names() %>%
  mutate(year = "2021") %>% 
  select(any_of(grad_variables))

#Weird thing with districts here -- versions with and without charters (different ids)

# Bind years
grad_bind = bind_rows(grad_17) %>% 
  bind_rows(grad_18) %>% 
  bind_rows(grad_19) %>% 
  bind_rows(grad_20) %>% 
  bind_rows(grad_21) %>%
  rename(any_of(key)) %>% 
  mutate(school_id = as.character(school_id), len_str = nchar(school_id)) %>% 
  mutate(school_id = if_else(len_str == 6, paste0("0", school_id), school_id)) %>% 
  select(-len_str)

compare_variables <- c("district.x", "school.x", "school_id", "gpercent_overall")

# Just look at schools that still exist in 2021
grad_rates <- school_list %>% 
  left_join(grad_bind, by = "school_id")

grad_rates_17 <- grad_rates %>% 
  filter(year == "2017") %>% 
  select(any_of(compare_variables)) %>% 
  rename(grad_percent_17 = "gpercent_overall")

grad_rates_21 <- grad_rates %>% 
  filter(year == "2021") %>% 
  select(any_of(compare_variables)) %>% 
  rename(grad_percent_21 = "gpercent_overall")

grad_increase <- grad_rates_17 %>% 
  inner_join(grad_rates_21) %>% 
  mutate(change_over_time = grad_percent_21 - grad_percent_17) %>% 
  mutate(percent_change_over_time = (change_over_time/grad_percent_17)*100) %>% 
  arrange(desc(change_over_time)) %>% 
  filter(school_id != "4701034", school_id != "1001630")


anti <- grad_rates_21 %>% 
  anti_join(grad_rates_17)

```

## Charter schools
```{r}

# What are the top 10 charter schools that have seen the greatest improvement in student reading scores in the last 5 years?
# What are the top 10 charter schools that have seen the greatest improvement in student math scores in the last 5 years?

charters_2017 <- schools_all_years %>% 
  filter(year == "2017", type_special == "charter") %>% 
  rename(e_pct_me_17 = e_pct_me, m_pct_me_17 = m_pct_me)

charters_2021 <- schools_all_years %>% 
  filter(year == "2021", type_special == "charter") %>% 
  rename(e_pct_me_21 = e_pct_me, m_pct_me_21 = m_pct_me)

charters_growth <- charters_2017 %>% 
  left_join(charters_2021, by = c("school_id", "type_x", "type_special", "district", "district_alt", "district_id", "school")) %>% 
  mutate(reading_change = e_pct_me_21 - e_pct_me_17, math_change = m_pct_me_21 - m_pct_me_17) %>% 
  mutate(reading_percent_change_over_time = (reading_change/e_pct_me_17)*100, math_percent_change_over_time = (math_change/m_pct_me_17)*100) %>% 
  select(school_id, school, type_x, type_special, district, district_alt, district_id, reading_change, reading_percent_change_over_time)






```

## Export data
```{r}
write_csv(teacher_retention, "etl_teacher_retention.csv")
write_csv(reading, "etl_reading.csv")
write_csv(reading_poverty, "etl_reading_poverty.csv")
write_csv(grad_increase, "etl_grad_increase.csv")
write_csv(charters_growth, "etl_charters_growth.csv")

```


-30-

